name: Add CI/CD pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Docker Image
        working-directory: coursera-spring-hello-world
        run: docker build -t spring-boot-app:latest .
